coopengo/coog-docker

scripts/anonymize_level_0.sql, scripts/anonymize_level_1.sql, scripts/anonymize_level_2.sql, scripts/anonymize_procedures.sql, scripts/anonymize_remove_procedures.sql
=> Add database anonymize scripts

CHANGELOG_EN, CHANGELOG_FR, bin/manage_db
=> Fix container name in change_admin_password

CHANGELOG_EN, CHANGELOG_FR, README.md, compose/database/rabbitmq.yml, defaults/rabbitmq/timeout.conf, env.base, env.custom.sample
=> rabbitmq: Increase default consumer timeout

CHANGELOG_EN, CHANGELOG_FR, compose/back/celery.yml, compose/back/coog.yml, compose/back/cron.yml
=> back: Depend on init completion before starting up

CHANGELOG_EN, CHANGELOG_FR, README.md, compose/back/common.yml, env.base, env.custom.sample
=> Add timezone configuration

CHANGELOG_EN, CHANGELOG_FR, compose/back/common.yml
=> back: Set default cache timeout to 0

bin/resources/anonymize_coog_db.sql
=> anonymisation: Anonymisation script should keep functionnal key

bin/configure, bin/down, bin/helpers/docker-compose, bin/manage_db, bin/tools/uwsgi_stats, bin/tools/uwsgi_tracebacks, bin/up
=> compatibility with docker-compose command + docker compose plugin + check minimum version

bin/resources/anonymize_coog_db.sql
=> anonymisation: [22.14] Anonymisation script should keep functionnal key (#39)

bin/resources/anonymize_coog_db.sql
=> anonymisation: [2.14] Anonymisation script should keep functionnal key (#39) 

bin/resources/anonymize_coog_db.sql
=> anonymisation: [2.12] Anonymisation script should keep functionnal key (#39)

bin/resources/anonymize_coog_db.sql
=> anonymisation: [2.10] Anonymisation script should keep functionnal key (#39) 

bin/resources/anonymize_coog_db.sql
=> Anonymisation: Add party interlocutor names anonymisation

bin/resources/anonymize_coog_db.sql
=> Anonymisation: [22.41] Add party interlocutor names anonymisation (#52)

bin/resources/anonymize_coog_db.sql
=> Anonymisation: [22.14] Add party interlocutor names anonymisation (#52)

bin/resources/anonymize_coog_db.sql
=> Anonymisation: [2.14] Add party interlocutor names anonymisation (#52)

bin/resources/anonymize_coog_db.sql
=> Anonymisation: [2.12] Add party interlocutor names anonymisation (#52)

bin/resources/anonymize_coog_db.sql
=> Anonymisation: [2.10] Add party interlocutor names anonymisation (#52)

env.base
=> revert MongoDB name variables to default values ​​to prevent side effects.
=> [API][MONGODB] Revert MongoDB name variables to default values

bin/manage_db
=> Manage_db: add feature to do a backup for mongo database and restore backups

bin/manage_db
=> Update postgresql process for backup and restore

.gitignore, bin/configure, compose/b2c/back.yml
=> Automatically inject postgres dependencies

CHANGELOG_EN, CHANGELOG_FR, compose/database/mongo.yml, env.base, env.custom.sample
=> Add configuration for mongo db maximum cache size

bin/resources/anonymize_coog_db.sql
=> [22.14] Add event log descriptions to the anonymisation script

CHANGELOG_EN, CHANGELOG_FR, bin/resources/anonymize_coog_db.sql
=> bin: Delete rule engine logs and error logs during database anonymisation

CHANGELOG_EN, CHANGELOG_FR, bin/resources/anonymize_coog_db.sql
Fix #PJAZZ-2054
Fix #PJAZZ-2092
=> bin: Delete party extra data during database anonymisation

compose/database/mongo.yml
=> Fix MongoDB version to 5

compose/back/coog_init.yml
=> Update coog command

CHANGELOG_EN, CHANGELOG_FR, bin/resources/anonymize_coog_db.sql
=> add missing anonymization on contract_life_agira

bin/resources/anonymize_coog_db.sql
=> anonymize: Fix extra data anonymisation

docker-compose.yml
#PELEC-209
Testé en local par Adrien
=> [24.14] Traefik: Update version to 3.4.0

docker-compose.yml
#PELEC-209
Testé en local par Adrien
=> [25.14] Traefik: Update version to 3.4.0

docker-compose.yml
#PELEC-209
Testé en local par Adrien
=> Traefik: Update version to 3.4.0
